
export const LOCATIONS = [
  "KUCHING",
  "SAMARAHAN",
  "SERIAN",
  "SRI AMAN",
  "BETONG",
  "SARIKEI",
  "SIBU",
  "KAPIT",
  "MUKAH",
  "BINTULU",
  "MIRI",
  "LIMBANG",
  "SABAH",
  "SEMENANJUNG MALAYSIA"
];

export const DURATIONS = [
  "1 HARI",
  "2 HARI",
  "3 HARI"
];

export const AGE_RANGES = [
  "20 TAHUN DAN KE BAWAH",
  "21-30 TAHUN",
  "31-40 TAHUN",
  "41-50 TAHUN",
  "51 TAHUN DAN KE ATAS"
];

export const ORGANIZERS = [
  "BAHAGIAN DAKWAH (HQ)",
  "BAHAGIAN KEMAJUAN KELUARGA ISLAM (HQ)",
  "BAHAGIAN KEMAJUAN INSTITUSI MASJID (HQ)",
  "BAHAGIAN PENGUKUHAN PENDIDIKAN ISLAM (HQ)",
  "BAHAGIAN PENGURUSAN HALAL (HQ)",
  "BAHAGIAN KEMAJUAN SAUDARA KITA (HQ)",
  "BAHAGIAN KAUNSELING SYARIE DAN PEMBANGUNAN PSIKOLOGI (HQ)",
  "BAHAGIAN PENGUATKUASAAN SYARIAH (HQ)",
  "BAHAGIAN PENDAKWAAN SYARIAH (HQ)",
  "BAHAGIAN PENTADBIRAN & PENGURUSAN SUMBER (HQ)",
  "UNIT KOMUNIKASI KORPORAT (HQ)",
  "UNIT INTEGRITI (HQ)",
  "BAHAGIAN PERANCANGAN & PENYELIDIKAN (HQ)",
  "UNIT PEMBANGUNAN (HQ)",
  "PEJABAT AGAMA ISLAM BAHAGIAN KUCHING (PAIB KUCHING)",
  "PEJABAT AGAMA ISLAM BAHAGIAN SAMARAHAN (PAIB SAMARAHAN)",
  "PEJABAT AGAMA ISLAM BAHAGIAN SERIAN (PAIB SERIAN)",
  "PEJABAT AGAMA ISLAM BAHAGIAN SRI AMAN (PAIB SRI AMAN)",
  "PEJABAT AGAMA ISLAM BAHAGIAN BETONG (PAIB BETONG)",
  "PEJABAT AGAMA ISLAM BAHAGIAN SARIKEI (PAIB SARIKEI)",
  "PEJABAT AGAMA ISLAM BAHAGIAN SIBU (PAIB SIBU)",
  "PEJABAT AGAMA ISLAM BAHAGIAN KAPIT (PAIB KAPIT)",
  "PEJABAT AGAMA ISLAM BAHAGIAN MUKAH (PAIB MUKAH)",
  "PEJABAT AGAMA ISLAM BAHAGIAN BINTULU (PAIB BINTULU)",
  "PEJABAT AGAMA ISLAM BAHAGIAN MIRI (PAIB MIRI)",
  "PEJABAT AGAMA ISLAM BAHAGIAN LIMBANG (PAIB LIMBANG)",
  "PEJABAT AGAMA ISLAM DAERAH DARO (PAID DARO)",
  "PEJABAT AGAMA ISLAM DAERAH LAWAS (PAID LAWAS)"
];

export const PROGRAM_VENUES = [
  // PEJABAT / KOMPLEKS ISLAM
  "KOMPLEKS ISLAM SARAWAK KUCHING (MAJMA' MALL)",
  "DEWAN IJTIMA' KOMPLEKS ISLAM SARAWAK KUCHING",
  "KOMPLEKS ISLAM SARAWAK SIBU",
  "PEJABAT AGAMA ISLAM BAHAGIAN BETONG",
  "PEJABAT AGAMA ISLAM BAHAGIAN BINTULU",
  "PEJABAT AGAMA ISLAM BAHAGIAN KAPIT",
  "PEJABAT AGAMA ISLAM BAHAGIAN KUCHING",
  "PEJABAT AGAMA ISLAM BAHAGIAN LAWAS",
  "PEJABAT AGAMA ISLAM BAHAGIAN LIMBANG",
  "PEJABAT AGAMA ISLAM BAHAGIAN MIRI",
  "PEJABAT AGAMA ISLAM BAHAGIAN MUKAH",
  "PEJABAT AGAMA ISLAM BAHAGIAN SARIKEI",
  "PEJABAT AGAMA ISLAM BAHAGIAN SERIAN",
  "PEJABAT AGAMA ISLAM BAHAGIAN SRI AMAN",
  
  // HOTEL (KUCHING)
  "56 HOTEL KUCHING",
  "GRAND MARGHERITA HOTEL KUCHING",
  "HARBOUR VIEW HOTEL KUCHING",
  "HILTON KUCHING",
  "IMPERIAL HOTEL KUCHING",
  "MERDEKA PALACE HOTEL KUCHING",
  "PULLMAN KUCHING",
  "RAIA HOTEL KUCHING",
  "RIVERSIDE MAJESTIC HOTEL KUCHING",
  "SERAPI HOTEL KUCHING",
  "SHERATON KUCHING HOTEL",
  "THE WATERFRONT HOTEL KUCHING",

  // HOTEL (LUAR KUCHING)
  "GOLDEN BAY HOTEL BINTULU",
  "HOTEL SERI MALAYSIA LAWAS",
  "IMPERIAL HOTEL MIRI",
  "JINHOLD HOTEL MIRI",
  "MERCURE MIRI CITY CENTRE",
  "MIRI MARRIOTT RESORT & SPA",
  "NU HOTEL BINTULU",
  "PARAMOUNT HOTEL SIBU",
  "PROMENADE HOTEL BINTULU",
  "PULLMAN MIRI WATERFRONT",
  "RH HOTEL SIBU",
  "THISTLE HOTEL JOHOR BAHRU",

  // MASJID & SURAU (KUCHING & SAMARAHAN)
  "MASJID AL-ABYAD MATANG JAYA",
  "MASJID AL-KAUTHAR GEDONG",
  "MASJID AL-MUTTAQIN KOTA SAMARAHAN",
  "MASJID DARUL ABIDIN JALAN ASTANA",
  "MASJID DARUL AKMAL SEMARIANG AMAN",
  "MASJID DARUL NAIM KAMPUNG LINTANG",
  "MASJID JAMEK NEGERI SARAWAK",
  "SURAU AL-GHAZALI UITM SAMARAHAN 2",
  "SURAU DARUL IMAN TAMAN SAMARINDAH",

  // MASJID & SURAU (LUAR KUCHING)
  "MASJID AL-AMIN SRI JAYA SRI AMAN",
  "MASJID AL-ASR KAMPUNG MERITAM LIMBANG",
  "MASJID AL-MUHSININ DARO",
  "MASJID AL-MUTTAQIN BEKENU",
  "MASJID AL-QUDDUS KAMPUNG BETANAK",
  "MASJID AN-NUR SIBU",
  "MASJID AR-RAHMAH KAMPUNG SEBERANG SARIKEI",
  "MASJID ASY-SYAKIRIN BINTULU",
  "MASJID AT-TAQWA MIRI",
  "MASJID BANDAR SRI AMAN (DEWAN KHULAFA AR-RASYIDIN)",
  "MASJID BESAR DARUL MAKMUR LAWAS",
  "MASJID DARUL AMILIN TAMAN PERMAI SIBU",
  "MASJID DARUL NAIM ENGKILILI",
  "MASJID DARUL SAADAH TAMAN SUSUR JAMBU SARIKEI",
  "MASJID DARUL SYAKIRIN KAMPUNG MUHIBBAH SRI AMAN",
  "MASJID JANNATUL FIRDAUS LIMBANG",
  "SURAU AL-MUHAJIRIN KAMPUNG WARISAN JEPAK BINTULU",
  "SURAU AN-NUR RPR SRI AMAN",

  // DEWAN & LAIN-LAIN
  "AUDITORIUM PUSTAKA NEGERI SARAWAK",
  "DEWAN MASYARAKAT DARO",
  "DEWAN MASYARAKAT KAMPUNG BUNGA RAYA LIMBANG",
  "DEWAN MASYARAKAT KAMPUNG MELAYU BELAGA",
  "DEWAN MASYARAKAT OYA",
  "DEWAN MASYARAKAT RANCHAN SERIAN",
  "DEWAN MASYARAKAT TANJUNG KEMBANG KABONG",
  "DEWAN SUARAH KOTA SAMARAHAN",
  "INSTITUT KOPERASI MALAYSIA ZON SARAWAK",
  "ISLAMIC INFORMATION CENTRE (IIC) KUCHING",
  "POLITEKNIK KUCHING SARAWAK",
  "SAINS TRAINING CENTRE ECO MALL SAMARIANG",
  "SARIKEI INNOVATION CENTRE (SIC)",
  "UNIMAS KOTA SAMARAHAN",

  // ONLINE
  "PLATFORM DALAM TALIAN (GOOGLE MEET / ZOOM)"
];


export const EDUCATION_LEVELS = [
  "SARJANA DAN KE ATAS",
  "IJAZAH SARJANA MUDA",
  "SPM/ DIPLOMA",
  "SRP/ PMR KE BAWAH",
  "TIDAK BERSEKOLAH"
];

export const PREMADE_COMMENTS = [
  "Sangat Bagus",
  "Baik",
  "Memuaskan",
  "Sederhana",
  "Perlu Penambahbaikan",
  "Tiada Komen"
];

export const PREMADE_SUGGESTIONS = [
  "Teruskan usaha",
  "Kekalkan prestasi",
  "Perbanyakkan program sebegini",
  "Masa perlu dipanjangkan",
  "Tiada Cadangan"
];

// Date Picker Constants
export const DAYS = Array.from({length: 31}, (_, i) => (i + 1).toString().padStart(2, '0'));
export const MONTHS = [
  "JANUARI", "FEBRUARI", "MAC", "APRIL", "MEI", "JUN",
  "JULAI", "OGOS", "SEPTEMBER", "OKTOBER", "NOVEMBER", "DISEMBER"
];
// Generate dynamic years (Current -1 to +2)
const currentYear = new Date().getFullYear();
export const YEARS = [currentYear - 1, currentYear, currentYear + 1, currentYear + 2].map(String);
