export const LOCATIONS = [
  "KUCHING",
  "SAMARAHAN",
  "SERIAN",
  "SRI AMAN",
  "BETONG",
  "SARIKEI",
  "SIBU",
  "KAPIT",
  "MUKAH",
  "BINTULU",
  "MIRI",
  "LIMBANG",
  "SABAH",
  "SEMENANJUNG MALAYSIA"
];

export const DURATIONS = [
  "1 HARI",
  "2 HARI",
  "3 HARI"
];

export const AGE_RANGES = [
  "20 TAHUN DAN KE BAWAH",
  "21-30 TAHUN",
  "31-40 TAHUN",
  "41-50 TAHUN",
  "51 TAHUN DAN KE ATAS"
];

export const ORGANIZERS = [
  "BAHAGIAN DAKWAH (HQ)",
  "BAHAGIAN KEMAJUAN KELUARGA ISLAM (HQ)",
  "BAHAGIAN KEMAJUAN INSTITUSI MASJID (HQ)",
  "BAHAGIAN PENGUKUHAN PENDIDIKAN ISLAM (HQ)",
  "BAHAGIAN PENGURUSAN HALAL (HQ)",
  "BAHAGIAN KEMAJUAN SAUDARA KITA (HQ)",
  "BAHAGIAN KAUNSELING SYARIE DAN PEMBANGUNAN PSIKOLOGI (HQ)",
  "BAHAGIAN PENGUATKUASAAN SYARIAH (HQ)",
  "BAHAGIAN PENDAKWAAN SYARIAH (HQ)",
  "BAHAGIAN PENTADBIRAN & PENGURUSAN SUMBER (HQ)",
  "UNIT KOMUNIKASI KORPORAT (HQ)",
  "UNIT INTEGRITI (HQ)",
  "BAHAGIAN PERANCANGAN & PENYELIDIKAN (HQ)",
  "UNIT PEMBANGUNAN (HQ)",
  "PEJABAT AGAMA ISLAM BAHAGIAN KUCHING (PAIB KUCHING)",
  "PEJABAT AGAMA ISLAM BAHAGIAN SAMARAHAN (PAIB SAMARAHAN)",
  "PEJABAT AGAMA ISLAM BAHAGIAN SERIAN (PAIB SERIAN)",
  "PEJABAT AGAMA ISLAM BAHAGIAN SRI AMAN (PAIB SRI AMAN)",
  "PEJABAT AGAMA ISLAM BAHAGIAN BETONG (PAIB BETONG)",
  "PEJABAT AGAMA ISLAM BAHAGIAN SARIKEI (PAIB SARIKEI)",
  "PEJABAT AGAMA ISLAM BAHAGIAN SIBU (PAIB SIBU)",
  "PEJABAT AGAMA ISLAM BAHAGIAN KAPIT (PAIB KAPIT)",
  "PEJABAT AGAMA ISLAM BAHAGIAN MUKAH (PAIB MUKAH)",
  "PEJABAT AGAMA ISLAM BAHAGIAN BINTULU (PAIB BINTULU)",
  "PEJABAT AGAMA ISLAM BAHAGIAN MIRI (PAIB MIRI)",
  "PEJABAT AGAMA ISLAM BAHAGIAN LIMBANG (PAIB LIMBANG)",
  "PEJABAT AGAMA ISLAM DAERAH DARO (PAID DARO)",
  "PEJABAT AGAMA ISLAM DAERAH LAWAS (PAID LAWAS)"
];

export const EDUCATION_LEVELS = [
  "SARJANA DAN KE ATAS",
  "IJAZAH SARJANA MUDA",
  "SPM/ DIPLOMA",
  "SRP/ PMR KE BAWAH",
  "TIDAK BERSEKOLAH"
];

export const PREMADE_COMMENTS = [
  "Sangat Bagus",
  "Baik",
  "Memuaskan",
  "Sederhana",
  "Perlu Penambahbaikan",
  "Tiada Komen"
];

export const PREMADE_SUGGESTIONS = [
  "Teruskan usaha",
  "Kekalkan prestasi",
  "Perbanyakkan program sebegini",
  "Masa perlu dipanjangkan",
  "Tiada Cadangan"
];

// Date Picker Constants
export const DAYS = Array.from({length: 31}, (_, i) => (i + 1).toString().padStart(2, '0'));
export const MONTHS = [
  "JANUARI", "FEBRUARI", "MAC", "APRIL", "MEI", "JUN",
  "JULAI", "OGOS", "SEPTEMBER", "OKTOBER", "NOVEMBER", "DISEMBER"
];
// Generate dynamic years (Current -1 to +2)
const currentYear = new Date().getFullYear();
export const YEARS = [currentYear - 1, currentYear, currentYear + 1, currentYear + 2].map(String);